/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'activity-log': RouteRecordInfo<'activity-log', '/activity-log', Record<never, never>, Record<never, never>>,
    'auth-login': RouteRecordInfo<'auth-login', '/auth/login', Record<never, never>, Record<never, never>>,
    'bookings': RouteRecordInfo<'bookings', '/bookings', Record<never, never>, Record<never, never>>,
    'clients': RouteRecordInfo<'clients', '/clients', Record<never, never>, Record<never, never>>,
    'payments': RouteRecordInfo<'payments', '/payments', Record<never, never>, Record<never, never>>,
    'policies': RouteRecordInfo<'policies', '/policies', Record<never, never>, Record<never, never>>,
    'policies-add-edit': RouteRecordInfo<'policies-add-edit', '/policies/add-edit', Record<never, never>, Record<never, never>>,
    'pricing': RouteRecordInfo<'pricing', '/pricing', Record<never, never>, Record<never, never>>,
    'providers': RouteRecordInfo<'providers', '/providers', Record<never, never>, Record<never, never>>,
    'requests': RouteRecordInfo<'requests', '/requests', Record<never, never>, Record<never, never>>,
    'services': RouteRecordInfo<'services', '/services', Record<never, never>, Record<never, never>>,
    'services-categories': RouteRecordInfo<'services-categories', '/services-categories', Record<never, never>, Record<never, never>>,
    'testing': RouteRecordInfo<'testing', '/testing', Record<never, never>, Record<never, never>>,
    'user-profile': RouteRecordInfo<'user-profile', '/user/profile', Record<never, never>, Record<never, never>>,
    'user-settings': RouteRecordInfo<'user-settings', '/user/settings', Record<never, never>, Record<never, never>>,
  }
}
